server:
  port: 9010
  servlet:
    context-path: /

spring:
  application:
    name: spring-cloud
  cloud:
    config:
      server:
        git:
          password: wl1351698648
          search-paths: CommonConfig
          uri: https://github.com/wulivictor/springcloud
          username: 1351698648@qq.com
        default-application-name: spring-cloud
      label: master
